CREATE TABLE `pay_in_dukpay` (
                                 `id` bigint NOT NULL AUTO_INCREMENT,
                                 `idempotency_key` varchar(128) NOT NULL,
                                 `merchant_name` varchar(128) NOT NULL,
                                 `reference_id` varchar(128) NOT NULL,
                                 `internal_transaction_id` varchar(128) NOT NULL,
                                 `vendor_transaction_id` varchar(128) DEFAULT NULL,
                                 `transfer_status` varchar(32) NOT NULL,
                                 `transaction_type` varchar(32) NOT NULL,
                                 `scheduled_time` timestamp NULL DEFAULT NULL,
                                 `submit_time` timestamp NOT NULL,
                                 `final_status_time` timestamp NULL DEFAULT NULL,
                                 `amount` bigint NOT NULL,
                                 `currency` varchar(8) NOT NULL,
                                 `country` varchar(8) NOT NULL,
                                 `payment_method` varchar(32) NOT NULL,
                                 `payment_flow` varchar(32) NOT NULL,
                                 `payment_info` json NOT NULL,
                                 `payer` json NOT NULL,
                                 `payer_comment` varchar(2048) DEFAULT NULL,
                                 `payee_comment` varchar(1024) DEFAULT NULL,
                                 `vendor_status_code` varchar(64) DEFAULT NULL,
                                 `vendor_status_message` varchar(1024) DEFAULT NULL,
                                 `transfer_status_code` varchar(64) DEFAULT NULL,
                                 `transfer_error_msg` varchar(1024) DEFAULT NULL,
                                 `response` varchar(4096) DEFAULT NULL,
                                 `version` int NOT NULL,
                                 `create_time` timestamp NOT NULL,
                                 `update_time` timestamp NOT NULL,
                                 `client_zone_id` varchar(32) NOT NULL,
                                 `raw_client_request` varchar(2048) NOT NULL,
                                 `vendorName` varchar(32) DEFAULT NULL,
                                 `flags` int NOT NULL,
                                 `settle_vendor` varchar(32) DEFAULT NULL,
                                 `vendor_transfer_details` json NOT NULL,
                                 `callback_url` varchar(256) DEFAULT NULL,
                                 `settled_time` timestamp NULL DEFAULT NULL,
                                 `refunded_amount` bigint NOT NULL DEFAULT '0',
                                 `risk_data` json DEFAULT NULL,
                                 `order_info` json DEFAULT NULL,
                                 PRIMARY KEY (`id`),
                                 KEY `pay_in_idempotency_key_index` (`merchant_name`,`idempotency_key`),
                                 KEY `pay_in_vendor_transaction_id_index` (`vendorName`,`vendor_transaction_id`),
                                 KEY `pay_in_internal_transaction_id_index` (`internal_transaction_id`)
) ENGINE=InnoDB AUTO_INCREMENT=508169 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;